name: HMS Platform CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  validate:
    name: Validate Platform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: |
          if [ -f docker-compose.yml ]; then
            docker compose config
          else
            echo "docker-compose.yml not found – skipping"
          fi

      - name: Validate Terraform
        run: |
          if [ -d terraform ]; then
            cd terraform
            terraform init -backend=false
            terraform validate
          else
            echo "Terraform directory not found – skipping"
          fi

  smoke:
    name: Smoke Tests (Playwright)
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (backend + frontend)
        run: |
          npm ci --prefix hms-backend
          npm ci --prefix hms-frontend

      - name: Install Playwright browsers
        working-directory: hms-frontend
        run: |
          npx playwright install --with-deps

      - name: Start backend (dev)
        run: |
          npm run dev --prefix hms-backend > backend.log 2>&1 & echo $! > backend.pid

      - name: Wait for backend to be healthy
        run: |
          npx wait-on http://localhost:4000/health --timeout 30000

      - name: Start frontend (dev)
        run: |
          npm run dev --prefix hms-frontend > frontend.log 2>&1 & echo $! > frontend.pid

      - name: Wait for frontend to be ready
        run: |
          npx wait-on http://localhost:5173/ --timeout 30000

      - name: Run Playwright smoke test
        run: |
          node scripts/playwright_capture.js
        env:
          NODE_ENV: test

      - name: Dump logs on failure
        if: failure()
        run: |
          echo "=== BACKEND LOG (last 200 lines) ==="
          tail -n 200 backend.log || true
          echo "=== FRONTEND LOG (last 200 lines) ==="
          tail -n 200 frontend.log || true

      - name: Cleanup background servers
        if: always()
        run: |
          if [ -f backend.pid ]; then kill $(cat backend.pid) || true; fi
          if [ -f frontend.pid ]; then kill $(cat frontend.pid) || true; fi

